const notes=[{name:'midnight.exe',text:'For the person who turns every five-minute queue into a full cinematic universe. May your aim stay clean and your chaos stay legendary.'},{name:'the 2am lobby',text:'Still not over that one game. Still not over how iconic you are either. Both facts remain true.'},{name:'coven signal 03',text:'You are equal parts soft heart, sharp tongue, and genuinely unmatched atmosphere.'},{name:'unknown but devoted',text:'May your playlists be criminally good, your year completely yours, and every room you enter know it just got better.'}];
const envelope=document.getElementById('envelope');
if(envelope){envelope.addEventListener('click',()=>{envelope.classList.add('open');envelope.setAttribute('aria-expanded','true');const letter=document.getElementById('letterText');letter.classList.add('visible');letter.setAttribute('aria-hidden','false')})}
const noteDialog=document.getElementById('noteDialog');
document.querySelectorAll('[data-note]').forEach(button=>button.addEventListener('click',()=>{const note=notes[Number(button.dataset.note)];document.getElementById('noteContent').innerHTML=`<h3>From ${note.name}</h3><p>${note.text}</p><p class="eyebrow">PLACEHOLDER FOR A REAL FRIEND MESSAGE</p>`;noteDialog.showModal()}));
const files=document.getElementById('filesDialog');const openFiles=document.getElementById('openFiles');if(openFiles)openFiles.addEventListener('click',()=>files.showModal());
document.querySelectorAll('.close-dialog').forEach(button=>button.addEventListener('click',()=>button.closest('dialog').close()));document.querySelectorAll('dialog').forEach(dialog=>dialog.addEventListener('click',event=>{if(event.target===dialog)dialog.close()}));
const form=document.getElementById('messageForm');if(form)form.addEventListener('submit',event=>{event.preventDefault();document.getElementById('formFeedback').textContent='Your message has been sealed. In the live build, it will arrive in the organiser review queue.';form.reset()});
const reducedMotion=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
if(!reducedMotion){const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting)entry.target.classList.add('in-view')}),{threshold:.14});document.querySelectorAll('.reveal').forEach(element=>observer.observe(element));window.addEventListener('pointermove',event=>{const hero=document.querySelector('.rizz-hero');if(!hero)return;const x=(event.clientX/window.innerWidth-.5)*5;const y=(event.clientY/window.innerHeight-.5)*5;hero.style.backgroundPosition=`calc(100% + ${x}px) calc(50% + ${y}px)`})}
