'use client';
import { AnimatePresence, motion, useReducedMotion } from 'framer-motion';
import { useEffect, useState } from 'react';
import { type MessageCard, type StoredMessage, mapStoredMessage } from '../src/data/mockData';
import { MemoryGallery } from './MemoryGallery';
import { MessageDialog } from './MessageDialog';
import { MessageGrid } from './MessageGrid';
import { OpeningLetter } from './OpeningLetter';
import { RelicNavigation } from './RelicNavigation';

interface RizzArchiveProps {}
export function RizzArchive(_: Readonly<RizzArchiveProps>) {
  const [openCard, setOpenCard] = useState<MessageCard | null>(null);
  const [messages, setMessages] = useState<readonly MessageCard[]>([]);
  const reduceMotion = useReducedMotion();
  const navigate = (target: string) => document.getElementById(target)?.scrollIntoView({ behavior: reduceMotion ? 'auto' : 'smooth' });
  useEffect(() => { const load = async () => { const response = await fetch('/api/letters', { cache: 'no-store' }); if (!response.ok) return; const result: { messages: StoredMessage[] } = await response.json(); setMessages(result.messages.map(mapStoredMessage)); }; void load(); const timer = window.setInterval(load, 15000); return () => window.clearInterval(timer); }, []);
  const finalUrl = process.env.NEXT_PUBLIC_FINAL_SURPRISE_URL;
  return <main className="overflow-hidden bg-ink"><section className="hero-scene relative min-h-screen px-5 pb-36 pt-28 md:px-14 lg:px-28"><div className="absolute inset-0 texture opacity-30"/><motion.div initial={{ opacity: 0, y: 28 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .8 }} className="relative max-w-2xl"><p className="text-xs font-bold tracking-[.2em] text-bone/70">A BIRTHDAY SURPRISE FOR RIZZ</p><h1 className="mt-5 font-display text-7xl font-black tracking-tighter md:text-9xl">Rizz.</h1><p className="mt-5 text-xl leading-relaxed text-bone/90">We made this little corner of the internet<br/>just to celebrate you.</p><button onClick={() => navigate('letter')} className="mt-10 border-b border-bone pb-2 text-xs font-bold tracking-[.16em]">START HERE ↓</button></motion.div><RelicNavigation onNavigate={navigate}/></section><OpeningLetter id="letter"/><section id="messages" className="px-5 py-24 md:px-14 lg:px-28"><div className="mx-auto max-w-6xl"><p className="text-xs font-bold tracking-[.18em] text-[#c8929b]">02 / NOTES FROM YOUR FRIENDS</p><div className="mt-5 grid gap-5 md:grid-cols-[1fr_.55fr]"><h2 className="font-display text-4xl leading-tight md:text-6xl">A lot of people<br/>wanted to say hi.</h2><p className="self-end leading-8 text-bone/70">Tap a card to read a friend’s birthday message. Photos, GIFs, and links appear inside the message they belong to.</p></div>{messages.length > 0 ? <MessageGrid cards={messages} onOpen={setOpenCard}/> : <div className="mt-12 grid min-h-56 place-items-center border border-dashed border-bone/25 p-8 text-center text-bone/60">Your friends’ messages will appear here as soon as they use the writing link.</div>}</div></section><MemoryGallery id="gallery"/><section id="finale" className="grid min-h-[75vh] place-items-center bg-[radial-gradient(circle,#30151c,transparent_45%),#090909] px-5 py-20 text-center"><motion.div initial={{ opacity: 0, scale: .96 }} whileInView={{ opacity: 1, scale: 1 }} viewport={{ once: true }} className="max-w-2xl border border-bone/20 p-10 md:p-16"><p className="text-xs font-bold tracking-[.18em] text-[#c8929b]">ONE LAST THING</p><h2 className="mt-5 font-display text-5xl leading-none md:text-8xl">Happy birthday,<br/><span className="text-[#c8929b]">Rizz.</span></h2><p className="mt-7 leading-8 text-bone/70">There is one last surprise waiting for you.</p>{finalUrl ? <a href={finalUrl} target="_blank" rel="noreferrer" className="mt-8 inline-block bg-bone px-6 py-4 text-xs font-bold tracking-[.14em] text-ink">OPEN YOUR SURPRISE ↗</a> : <span className="mt-8 inline-block border border-bone/30 px-6 py-4 text-xs font-bold tracking-[.14em] text-bone/50">SURPRISE LINK COMING SOON</span>}</motion.div></section><AnimatePresence>{openCard && <MessageDialog card={openCard} onClose={() => setOpenCard(null)}/>}</AnimatePresence></main>;
}
